---
**Query #1**
-- What is the unique count and total amount for each transaction type?

    SELECT TXN_TYPE, COUNT(DISTINCT CUSTOMER_ID), SUM(TXN_AMOUNT)
    FROM DATA_BANK.CUSTOMER_TRANSACTIONS
    GROUP BY TXN_TYPE;

| txn_type   | count | sum     |
| ---------- | ----- | ------- |
| deposit    | 500   | 1359168 |
| purchase   | 448   | 806537  |
| withdrawal | 439   | 793003  |

---
**Query #3**
-- For each month - how many Data Bank customers make more than 1 deposit and either 1 purchase or 1 withdrawal in a single month?

WITH DEPOSIT AS (
  SELECT CUSTOMER_ID, EXTRACT(MONTH FROM TXN_DATE) AS MONTH_NUM, COUNT(*) AS DEPOSIT_COUNT
  FROM DATA_BANK.CUSTOMER_TRANSACTIONS
  WHERE TXN_TYPE LIKE 'DEPOSIT'
  GROUP BY MONTH_NUM, CUSTOMER_ID
), WITHDRAWAL AS (
  SELECT CUSTOMER_ID, EXTRACT(MONTH FROM TXN_DATE) AS MONTH_NUM, COUNT(*) AS WITHDRAWAL_COUNT
  FROM DATA_BANK.CUSTOMER_TRANSACTIONS
  WHERE TXN_TYPE LIKE 'WITHDRAWAL'
   GROUP BY MONTH_NUM, CUSTOMER_ID
), PURCHASE AS (
  SELECT CUSTOMER_ID, EXTRACT(MONTH FROM TXN_DATE) AS MONTH_NUM, COUNT(*) AS PURCHASE_COUNT
  FROM DATA_BANK.CUSTOMER_TRANSACTIONS
  WHERE TXN_TYPE LIKE 'PURCHASE'
   GROUP BY MONTH_NUM, CUSTOMER_ID
)
SELECT D.MONTH_NUM, D.CUSTOMER_ID, DEPOSIT_COUNT, WITHDRAWAL_COUNT, PURCHASE_COUNT
FROM DEPOSIT AS D JOIN WITHDRAWAL AS W ON D.CUSTOMER_ID = W.CUSTOMER_ID AND D.MONTH_NUM = W.MONTH_NUM JOIN PURCHASE AS P ON D.CUSTOMER_ID = P.CUSTOMER_ID AND D.MONTH_NUM = P.MONTH_NUM
WHERE DEPOSIT_COUNT > 1 AND (WITHDRAWAL_COUNT > 1 OR PURCHASE_COUNT > 1);
