DROP TABLE IF EXISTS CLEAN_customer_orders;
CREATE TEMP TABLE CLEAN_customer_orders AS(
  SELECT PIZZA_RUNNER.CUSTOMER_ORDERS.ORDER_ID,
  PIZZA_RUNNER.CUSTOMER_ORDERS.CUSTOMER_ID,
  PIZZA_RUNNER.CUSTOMER_ORDERS.PIZZA_ID,
  CASE 
  WHEN PIZZA_RUNNER.CUSTOMER_ORDERS.EXCLUSIONS = '' THEN NULL
  WHEN PIZZA_RUNNER.CUSTOMER_ORDERS.EXCLUSIONS = 'null' THEN NULL
  ELSE PIZZA_RUNNER.CUSTOMER_ORDERS.EXCLUSIONS
  END AS EXCLUSIONS,
  CASE
  WHEN PIZZA_RUNNER.CUSTOMER_ORDERS.EXTRAS = '' THEN NULL
  WHEN PIZZA_RUNNER.CUSTOMER_ORDERS.EXTRAS = 'null' THEN NULL
  ELSE PIZZA_RUNNER.CUSTOMER_ORDERS.EXTRAS
  END AS EXTRAS,
  PIZZA_RUNNER.CUSTOMER_ORDERS.ORDER_TIME
  
  FROM PIZZA_RUNNER.CUSTOMER_ORDERS
);


SELECT * FROM CLEAN_CUSTOMER_ORDERS;
